name: Mekanism Native NSP Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Tools and Compile
        run: |
          # 1. On force la mise à jour et l'installation de nacp
          sudo dkp-pacman -Syyu --noconfirm
          sudo dkp-pacman -S --noconfirm switch-tools
          
          # 2. On définit les chemins
          export DEVKITPRO=/opt/devkitpro
          export DEVKITA64=$DEVKITPRO/devkitA64
          export PATH=$PATH:$DEVKITPRO/tools/bin:$DEVKITA64/bin
          
          # 3. Génération du NACP (L'identité du jeu)
          # On l'appelle par son nom maintenant qu'il est installé proprement
          nacp -c --name "Mekanism" --author "Pamplemouche" --version "1.0.0" Mekanism.nacp
          
          # 4. Compilation du binaire (ELF)
          aarch64-none-elf-gcc -O2 -Wall -I$DEVKITPRO/libnx/include main.c -o Mekanism.elf -specs=$DEVKITPRO/libnx/switch.specs -L$DEVKITPRO/libnx/lib -lnx

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Mekanism-NSP-Parts
          path: |
            Mekanism.elf
            Mekanism.nacp
